---
# Write your playbook below.
# Replace these contents with the tasks you'd like to complete and the modules you need.
# For help getting started, check out https://www.redhat.com/en/topics/automation/what-is-an-ansible-playbook
# Ansible playbook to automate the setup of a Website deployment on rocky linux server

# Disable root SSH login for security
#fukass comment
- name: Website deployment automation script - Disable Root SSH Login
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
   - name: PermitRootLogin set to no
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '^#?PermitRootLogin'
       line: 'PermitRootLogin no'
       state: present
   - name: Restart sshd
     ansible.builtin.service:
       name: sshd
       state: restarted

- name: Website deployment automation script - Firewall Ports and Reload
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
   - name: Enable ports
     ansible.posix.firewalld:
       port: "{{ item }}/tcp"
       permanent: true
       state: enabled
     loop:
      - 80
      - 443
   - name: Reload firewalld
     ansible.builtin.service:
       name: firewalld
       state: reloaded
       enabled: true

- name: Website deployment automation script - Install and Enable HTTPD
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: 
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
- name: Website deployment automation script - pull website content from GitHub
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: