---
# Write your playbook below.
# Replace these contents with the tasks you'd like to complete and the modules you need.
# For help getting started, check out https://www.redhat.com/en/topics/automation/what-is-an-ansible-playbook
# Ansible playbook to automate the setup of a Website deployment on rocky linux server

# Disable root SSH login for security
#fukass comment
- name: Website deployment automation script - Disable Root SSH Login
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
   - name: PermitRootLogin set to no
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '^#?PermitRootLogin'
       line: 'PermitRootLogin no'
       state: present
   - name: Restart sshd
     ansible.builtin.service:
       name: sshd
       state: restarted

- name: Website deployment automation script - Firewall Ports and Reload
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
   - name: Enable ports
     ansible.posix.firewalld:
       port: "{{ item }}/tcp"
       permanent: true
       state: enabled
     loop:
      - 80
      - 443
   - name: Reload firewalld
     ansible.builtin.service:
       name: firewalld
       state: reloaded
       enabled: true

- name: Website deployment automation script - Install and Enable HTTPD
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: 
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

- name: Website deployment automation script - Install and Enable MySQL and MariaDB
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install MySQL server package
      ansible.builtin.yum:
        name: mysql-server
        state: present
    - name: Install MariaDB
      ansible.builtin.yum:
        name: mariadb
        state: present
    - name: Install MariaDB server package
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysql-server
        state: started
        enabled: true
    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

- name: Website deployment automation script - MySQL Secure Installation
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    mysql_root_password: "SavCone255!"
  tasks: 
    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present
    - name: Remove Anon Users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
    - name: Disable remote root login
      mysql_user:
        name: root
        host: '%'
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
    - name: Remove test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

- name: Website deployment automation script - Move basicwebpage.html from github clone to /var/www/html/
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Moving basicwebpage.html to /var/www/html/
      ansible.builtin.copy:
        src: /home/champuser/Sys-255-Final-Project/sysfinal/basicwebpage.html
        dest: /var/www/html/index.html
        mode: '0644'